### ISSUE TITLE
Docker build

### ISSUE THREAD

**Issue by brettowe** [Zoxc/crusader#15]
I made a docker build script so one can do a quick deploy on a server for easier testing.
[Dockerfile.txt](https://github.com/Zoxc/crusader/files/14594167/Dockerfile.txt)
one flaw with this as is, the cargo build script wants to build gui side also and I didn't see how to tell it to not without a manual edit.
as such I included a cargo update line so if someone edits the build list it builds without throwing errors.

**Comment by tangentsoft** [comment]
The `Dockerfile` attached above has a number of problems that needed fixing to get it to build against the current version:

1. Syntax tweaks: capital "AS" in the first line, etc.
2. Skip "cargo update" to avoid invalidating all subsequent layers. Use the locked versions of the crates otherwise. Update on the host side only when necessary, which will copy the result in with the `COPY` step.
3. Use explicit "fetch" to avoid redoing that work if the `build` step fails.
4. Put the result into the second stage's preexisting `/bin` dir, not a separate `/app` dir.
5. Most important, build only the server binary, not the GUI. The GUI should run outside the container. Without this step, you need to bring in a lot more dependencies into the first stage: fontconfig, freetype, expat, zlib…

Copy the text below into a `Dockerfile` at the Crusader root, then build with `docker build --tag crusader .`:

``` Dockerfile
FROM cgr.dev/chainguard/rust:latest-dev AS build
USER root
COPY ./src ./
RUN cargo fetch
RUN cargo build --release --package crusader

FROM cgr.dev/chainguard/wolfi-base:latest
COPY --from=build /work/target/release/crusader /bin/
RUN apk add --no-cache libgcc

EXPOSE 35481
ENTRYPOINT [ "/bin/crusader", "serve" ]
```

**Comment by Zoxc** [comment]
I've added a Dockerfile to the repo for the server now.

**Comment by tangentsoft** [comment]
It's not particular to Rust at all. Each command you give (`RUN` in this case) gets baked to an immutable layer. When you say:

```
RUN cargo fetch
RUN cargo build …
```

the fetch steps get saved to a single layer and are never repeated until one of the layers above changes, in this case most likely because the `COPY src` contents change, thus sending new `Cargo.lock/toml` files.

Doing it in two steps like this instead of depending on `cargo build` to do an implicit fetch saves repeated fetches while you're debugging a build problem.
